version: "3.8"

services:
  react-app:
    build: .
    ports:
      - "3000:3000"  # React Vite 기본 포트 매핑
    volumes:
      - .:/app  # 로컬 파일을 컨테이너에 마운트 (자동 반영됨)
      - /app/node_modules  # node_modules는 컨테이너 내부에서만 유지
    stdin_open: true
    tty: true
